---
# tasks file for ansible-role-jre

# ----- Gather facts & sanity checks -----
- name: "all | ensure remote os supported"
  fail: "Unsupported. This role is depends on Linux."
  when: ansible_system not in ['Linux']


# ----- Install Oracle JRE -----
- name: "Oracle JRE | check for current jre installation"
  stat: "path={{ jre_oracle_install_dir }}/bin"
  register: jre_oracle_bin
  when: ansible_system in ['Linux'] and jre_prefer_oracle


- name: "Oracle JRE | ensure jre install directory exists"
  sudo: Yes
  file:
    path: "{{ jre_oracle_install_dir }}"
    state: directory
  when: ansible_system in ['Linux'] and jre_prefer_oracle


- name: "Oracle JRE | download jre binary tarball"
  uri:
    url: "{{ jre_oracle_download_url }}"
    HEADER_Referer: "{{ jre_oracle_download_referrer }}"
    HEADER_Cookie: "{{ jre_oracle_download_cookie }}"
    dest: "{{ jre_oracle_download_dest }}"
  when: ansible_system in ['Linux'] and jre_prefer_oracle and not jre_oracle_bin.stat.exists


- name: "Oracle JRE | unarchive jre binary to its install directory"
  sudo: Yes
  command: tar xvf {{ jre_oracle_download_dest }} -C {{ jre_oracle_install_dir }} --strip-components=1
  args:
    creates: "{{ jre_oracle_install_dir }}/bin"
  when: ansible_system in ['Linux'] and jre_prefer_oracle and not jre_oracle_bin.stat.exists


- name: "Oracle JRE | ensure alternatives with jre bins"
  sudo: Yes
  alternatives:
    link: "/usr/bin/{{ item }}"
    name: "{{ item }}"
    path: "{{ jre_oracle_install_dir }}/bin/{{ item }}"
  with_items: jre_oracle_install_bins
  when: ansible_system in ['Linux'] and jre_prefer_oracle
