# Install Oracle JRE
---
- name: "Oracle | check for current jre installation"
  stat: "path={{ jre_oracle_install_dir }}/bin"
  register: jre_oracle_bin

- name: "Oracle | ensure jre install directory exists"
  become: Yes
  file:
    path: "{{ jre_oracle_install_dir }}"
    state: directory

- name: "Oracle | download jre binary tarball"
  uri:
    url: "{{ jre_oracle_download_url }}"
    HEADER_Referer: "{{ jre_oracle_download_referrer }}"
    HEADER_Cookie: "{{ jre_oracle_download_cookie }}"
    dest: "{{ jre_oracle_download_dest }}"
    creates: "{{ jre_oracle_download_dest }}"
  when: not jre_oracle_bin.stat.exists

- name: "Oracle | unarchive jre binary to its install directory"
  become: Yes
  unarchive: > 
    src="{{ jre_oracle_download_dest }}" 
    dest="{{ jre_oracle_install_dir }}" 
    creates="{{ jre_oracle_install_dir }}/bin"
    extra_opts="--strip-components=1"
    copy=no
  # Work-around waiting for PR merge https://github.com/ansible/ansible-modules-core/issues/2480
  ignore_errors: yes
  when: not jre_oracle_bin.stat.exists

- name: "Oracle | ensure alternatives with jre bins"
  become: Yes
  alternatives:
    link: "/usr/bin/{{ item }}"
    name: "{{ item }}"
    path: "{{ jre_oracle_install_dir }}/bin/{{ item }}"
  with_items: "{{ jre_oracle_install_bins }}"
...
